export type SignoNome =
  | 'Áries'
  | 'Touro'
  | 'Gêmeos'
  | 'Câncer'
  | 'Leão'
  | 'Virgem'
  | 'Libra'
  | 'Escorpião'
  | 'Sagitário'
  | 'Capricórnio'
  | 'Aquário'
  | 'Peixes';

export type TarotCard = {
  id: number;
  nome: string;
  imagem: any;
  interpretacaoNormal: string;
  interpretacaoInvertida: string;
};



export const TAROT_CARDS: TarotCard[] = [
  {
    id: 1,
    nome: 'O Mago',
    imagem: require('../assets/images/arcanos/rider-waite/mago.png'),
    interpretacaoNormal: 'Iniciativa, habilidade e poder de manifestar.',
    interpretacaoInvertida: 'Impulsividade, manipulação ou energia dispersa.',
  },
  {
    id: 2,
    nome: 'A Sacerdotisa',
    imagem: require('../assets/images/arcanos/rider-waite/sacerdotisa.png'),
    interpretacaoNormal: 'Intuição forte e leitura profunda do cenário.',
    interpretacaoInvertida: 'Bloqueio intuitivo ou segredos mal resolvidos.',
  },
  {
    id: 3,
    nome: 'A Imperatriz',
    imagem: require('../assets/images/arcanos/rider-waite/imperatriz.png'),
    interpretacaoNormal: 'Crescimento, criatividade e fertilidade de ideias.',
    interpretacaoInvertida: 'Estagnação criativa ou excesso de conforto.',
  },
  {
    id: 4,
    nome: 'O Imperador',
    imagem: require('../assets/images/arcanos/rider-waite/imperador.png'),
    interpretacaoNormal: 'Estrutura, liderança e segurança material.',
    interpretacaoInvertida: 'Rigidez, controle excessivo ou autoritarismo.',
  },
  {
    id: 5,
    nome: 'O Hierofante',
    imagem: require('../assets/images/arcanos/rider-waite/hierofante.png'),
    interpretacaoNormal: 'Aprendizado, tradição e aconselhamento.',
    interpretacaoInvertida: 'Dogmas, teimosia ou ruptura com referências.',
  },
  {
    id: 6,
    nome: 'Os Enamorados',
    imagem: require('../assets/images/arcanos/rider-waite/enamorados.png'),
    interpretacaoNormal: 'Escolhas alinhadas com valores e afeto.',
    interpretacaoInvertida: 'Dúvida, indecisão e conflitos internos.',
  },
  {
    id: 7,
    nome: 'O Carro',
    imagem: require('../assets/images/arcanos/rider-waite/carro.png'),
    interpretacaoNormal: 'Avanço, foco e conquista por disciplina.',
    interpretacaoInvertida: 'Falta de direção ou pressa sem estratégia.',
  },
  {
    id: 8,
    nome: 'A Justiça',
    imagem: require('../assets/images/arcanos/rider-waite/justica.png'),
    interpretacaoNormal: 'Clareza, equilíbrio e decisões justas.',
    interpretacaoInvertida: 'Autojulgamento, injustiça ou negação de fatos.',
  },
  {
    id: 9,
    nome: 'O Eremita',
    imagem: require('../assets/images/arcanos/rider-waite/eremita.png'),
    interpretacaoNormal: 'Recolhimento produtivo e sabedoria.',
    interpretacaoInvertida: 'Isolamento excessivo e distanciamento.',
  },
  {
    id: 10,
    nome: 'A Roda da Fortuna',
    imagem: require('../assets/images/arcanos/rider-waite/roda.png'),
    interpretacaoNormal: 'Viradas positivas e mudanças de ciclo.',
    interpretacaoInvertida: 'Imprevisibilidade e sensação de perda de controle.',
  },
  {
    id: 11,
    nome: 'A Força',
    imagem: require('../assets/images/arcanos/rider-waite/forca.png'),
    interpretacaoNormal: 'Coragem emocional e domínio interno.',
    interpretacaoInvertida: 'Insegurança, cansaço ou reatividade.',
  },
  {
    id: 12,
    nome: 'O Pendurado',
    imagem: require('../assets/images/arcanos/rider-waite/pendurado.png'),
    interpretacaoNormal: 'Pausa necessária e nova perspectiva.',
    interpretacaoInvertida: 'Resistência à mudança e vitimização.',
  },
  {
    id: 13,
    nome: 'A Morte',
    imagem: require('../assets/images/arcanos/rider-waite/morte.png'),
    interpretacaoNormal: 'Fim de ciclo e transformação profunda.',
    interpretacaoInvertida: 'Apego ao passado e dificuldade de encerrar fases.',
  },
  {
    id: 14,
    nome: 'A Temperança',
    imagem: require('../assets/images/arcanos/rider-waite/temperanca.png'),
    interpretacaoNormal: 'Harmonia, paciência e cura gradual.',
    interpretacaoInvertida: 'Desequilíbrio e exageros recorrentes.',
  },
  {
    id: 15,
    nome: 'O Diabo',
    imagem: require('../assets/images/arcanos/rider-waite/diabo.png'),
    interpretacaoNormal: 'Confronto com desejos, apegos e sombras.',
    interpretacaoInvertida: 'Libertação de padrões tóxicos e vícios.',
  },
  {
    id: 16,
    nome: 'A Torre',
    imagem: require('../assets/images/arcanos/rider-waite/torre.png'),
    interpretacaoNormal: 'Queda de estruturas e verdade revelada.',
    interpretacaoInvertida: 'Medo da ruptura e crise prolongada.',
  },
  {
    id: 17,
    nome: 'A Estrela',
    imagem: require('../assets/images/arcanos/rider-waite/estrela.png'),
    interpretacaoNormal: 'Esperança, inspiração e renovação.',
    interpretacaoInvertida: 'Desânimo temporário e perda de fé.',
  },
  {
    id: 18,
    nome: 'A Lua',
    imagem: require('../assets/images/arcanos/rider-waite/lua.png'),
    interpretacaoNormal: 'Sensibilidade alta e leitura simbólica.',
    interpretacaoInvertida: 'Confusão emocional ou ilusões.',
  },
  {
    id: 19,
    nome: 'O Sol',
    imagem: require('../assets/images/arcanos/rider-waite/sol.png'),
    interpretacaoNormal: 'Vitalidade, clareza e expansão.',
    interpretacaoInvertida: 'Ego em excesso ou dificuldade em celebrar.',
  },
  {
    id: 20,
    nome: 'O Julgamento',
    imagem: require('../assets/images/arcanos/rider-waite/julgamento.png'),
    interpretacaoNormal: 'Chamado interno e despertar de consciência.',
    interpretacaoInvertida: 'Autojulgamento severo e adiamento de decisões.',
  },
  {
    id: 21,
    nome: 'O Mundo',
    imagem: require('../assets/images/arcanos/rider-waite/mundo.png'),
    interpretacaoNormal: 'Conclusão bem-sucedida e realização.',
    interpretacaoInvertida: 'Ciclo pendente e sensação de incompletude.',
  },
  {
    id: 22,
    nome: 'O Louco',
    imagem: require('../assets/images/arcanos/rider-waite/louco.png'),
    interpretacaoNormal: 'Recomeço, espontaneidade e coragem de tentar.',
    interpretacaoInvertida: 'Imprudência ou medo de começar.',
  },
];

const TAROT_MINOR_CARDS: TarotCard[] = [
  {
    id: 23,
    nome: 'Ás de Copas',
    imagem: require('../assets/images/arcanos/rider-waite/ascopas.png'),
    interpretacaoNormal: 'Novo início emocional, amor puro e abertura do coração.',
    interpretacaoInvertida: 'Bloqueio emocional, sentimentos reprimidos ou medo de se abrir.',
  },
  {
    id: 24,
    nome: '2 de Copas',
    imagem: require('../assets/images/arcanos/rider-waite/2copas.png'),
    interpretacaoNormal: 'Parceria equilibrada, conexão mútua e troca genuína.',
    interpretacaoInvertida: 'Desequilíbrio na relação, mal-entendidos ou afastamento.',
  },
  {
    id: 25,
    nome: '3 de Copas',
    imagem: require('../assets/images/arcanos/rider-waite/3copas.png'),
    interpretacaoNormal: 'Celebração, amizades fortes e alegria compartilhada.',
    interpretacaoInvertida: 'Isolamento, fofoca ou excessos nas celebrações.',
  },
  {
    id: 26,
    nome: '4 de Copas',
    imagem: require('../assets/images/arcanos/rider-waite/4copas.png'),
    interpretacaoNormal: 'Pausa para reflexão e reavaliação do que tem valor.',
    interpretacaoInvertida: 'Apatia prolongada ou recusa em enxergar o que está disponível.',
  },
  {
    id: 27,
    nome: '5 de Copas',
    imagem: require('../assets/images/arcanos/rider-waite/5copas.png'),
    interpretacaoNormal: 'Luto necessário que abre espaço para recomeço.',
    interpretacaoInvertida: 'Preso no passado, dificuldade em aceitar a perda e seguir em frente.',
  },
  {
    id: 28,
    nome: '6 de Copas',
    imagem: require('../assets/images/arcanos/rider-waite/6copas.png'),
    interpretacaoNormal: 'Nostalgia positiva, inocência e conexões do passado.',
    interpretacaoInvertida: 'Idealização do passado impedindo o crescimento no presente.',
  },
  {
    id: 29,
    nome: '7 de Copas',
    imagem: require('../assets/images/arcanos/rider-waite/7copas.png'),
    interpretacaoNormal: 'Imaginação fértil e múltiplas possibilidades à vista.',
    interpretacaoInvertida: 'Ilusão, escapismo ou dificuldade de sair do mundo dos sonhos.',
  },
  {
    id: 30,
    nome: '8 de Copas',
    imagem: require('../assets/images/arcanos/rider-waite/8copas.png'),
    interpretacaoNormal: 'Coragem de ir embora em busca de algo mais significativo.',
    interpretacaoInvertida: 'Medo de abandonar o que já não serve, estagnação por comodismo.',
  },
  {
    id: 31,
    nome: '9 de Copas',
    imagem: require('../assets/images/arcanos/rider-waite/9copas.png'),
    interpretacaoNormal: 'Realização de desejo, satisfação e gratidão plena.',
    interpretacaoInvertida: 'Autossabotagem, ingratidão ou prazer vazio sem propósito.',
  },
  {
    id: 32,
    nome: '10 de Copas',
    imagem: require('../assets/images/arcanos/rider-waite/10copas.png'),
    interpretacaoNormal: 'Plenitude emocional, harmonia familiar e felicidade duradoura.',
    interpretacaoInvertida: 'Conflitos no lar, relações superficiais ou felicidade fingida.',
  },
  {
    id: 33,
    nome: 'Page de Copas',
    imagem: require('../assets/images/arcanos/rider-waite/pagecopas.png'),
    interpretacaoNormal: 'Mensagem afetiva, criatividade e abertura para o novo.',
    interpretacaoInvertida: 'Imaturidade emocional ou dificuldade em expressar sentimentos.',
  },
  {
    id: 34,
    nome: 'Cavaleiro de Copas',
    imagem: require('../assets/images/arcanos/rider-waite/cavcopas.png'),
    interpretacaoNormal: 'Romantismo, seguir o coração com charme e ideais.',
    interpretacaoInvertida: 'Sedução vazia, promessas não cumpridas ou excesso de fantasia.',
  },
  {
    id: 35,
    nome: 'Rainha de Copas',
    imagem: require('../assets/images/arcanos/rider-waite/rainhacopas.png'),
    interpretacaoNormal: 'Intuição poderosa, empatia profunda e cuidado genuíno.',
    interpretacaoInvertida: 'Dependência emocional, manipulação afetiva ou sensibilidade excessiva.',
  },
  {
    id: 36,
    nome: 'Rei de Copas',
    imagem: require('../assets/images/arcanos/rider-waite/reicopas.png'),
    interpretacaoNormal: 'Maturidade emocional, sabedoria e diplomacia nos sentimentos.',
    interpretacaoInvertida: 'Frieza emocional, instabilidade ou manipulação disfarçada de cuidado.',
  },

  {
    id: 37,
    nome: 'Ás de Paus',
    imagem: require('../assets/images/arcanos/rider-waite/aspaus.png'),
    interpretacaoNormal: 'Faísca criativa, inspiração e impulso para agir.',
    interpretacaoInvertida: 'Energia travada, falta de motivação ou ideias sem execução.',
  },
  {
    id: 38,
    nome: '2 de Paus',
    imagem: require('../assets/images/arcanos/rider-waite/2paus.png'),
    interpretacaoNormal: 'Planejamento audacioso e visão de futuro clara.',
    interpretacaoInvertida: 'Medo de sair da zona de conforto ou planos sem ação.',
  },
  {
    id: 39,
    nome: '3 de Paus',
    imagem: require('../assets/images/arcanos/rider-waite/3paus.png'),
    interpretacaoNormal: 'Expansão, espera confiante e horizontes se abrindo.',
    interpretacaoInvertida: 'Impaciência, atrasos ou falta de visão de longo prazo.',
  },
  {
    id: 40,
    nome: '4 de Paus',
    imagem: require('../assets/images/arcanos/rider-waite/4paus.png'),
    interpretacaoNormal: 'Celebração de conquistas e bases sólidas construídas.',
    interpretacaoInvertida: 'Instabilidade no lar ou festa prematura sem estrutura real.',
  },
  {
    id: 41,
    nome: '5 de Paus',
    imagem: require('../assets/images/arcanos/rider-waite/5paus.png'),
    interpretacaoNormal: 'Debates produtivos e competição que impulsiona crescimento.',
    interpretacaoInvertida: 'Conflitos desnecessários, briga por ego ou caos sem propósito.',
  },
  {
    id: 42,
    nome: '6 de Paus',
    imagem: require('../assets/images/arcanos/rider-waite/6paus.png'),
    interpretacaoNormal: 'Vitória merecida, reconhecimento e confiança renovada.',
    interpretacaoInvertida: 'Arrogância, reconhecimento tardio ou vitória sem base sólida.',
  },
  {
    id: 43,
    nome: '7 de Paus',
    imagem: require('../assets/images/arcanos/rider-waite/7paus.png'),
    interpretacaoNormal: 'Defesa do que é seu com força e posição de vantagem.',
    interpretacaoInvertida: 'Cansaço de lutar, rendição prematura ou paranoia excessiva.',
  },
  {
    id: 44,
    nome: '8 de Paus',
    imagem: require('../assets/images/arcanos/rider-waite/8paus.png'),
    interpretacaoNormal: 'Movimento rápido, notícias chegando e energia em alta.',
    interpretacaoInvertida: 'Precipitação, mensagens mal interpretadas ou correria sem foco.',
  },
  {
    id: 45,
    nome: '9 de Paus',
    imagem: require('../assets/images/arcanos/rider-waite/9paus.png'),
    interpretacaoNormal: 'Resiliência e força para aguentar até o fim.',
    interpretacaoInvertida: 'Paranoia, esgotamento extremo ou desistência na reta final.',
  },
  {
    id: 46,
    nome: '10 de Paus',
    imagem: require('../assets/images/arcanos/rider-waite/10paus.png'),
    interpretacaoNormal: 'Responsabilidade pesada sendo carregada com determinação.',
    interpretacaoInvertida: 'Colapso por sobrecarga, recusa em pedir ajuda ou burnout.',
  },
  {
    id: 47,
    nome: 'Page de Paus',
    imagem: require('../assets/images/arcanos/rider-waite/pagepaus.png'),
    interpretacaoNormal: 'Entusiasmo juvenil, curiosidade e início de novos projetos.',
    interpretacaoInvertida: 'Impulsividade sem planejamento ou entusiasmo que não se sustenta.',
  },
  {
    id: 48,
    nome: 'Cavaleiro de Paus',
    imagem: require('../assets/images/arcanos/rider-waite/cavpaus.png'),
    interpretacaoNormal: 'Ação corajosa, paixão e aventura com energia total.',
    interpretacaoInvertida: 'Imprudência, projetos abandonados no meio ou energia dispersa.',
  },
  {
    id: 49,
    nome: 'Rainha de Paus',
    imagem: require('../assets/images/arcanos/rider-waite/rainhapaus.png'),
    interpretacaoNormal: 'Confiança magnética, liderança e independência poderosa.',
    interpretacaoInvertida: 'Dominação, ciúme ou energia que intimida em vez de inspirar.',
  },
  {
    id: 50,
    nome: 'Rei de Paus',
    imagem: require('../assets/images/arcanos/rider-waite/reipaus.png'),
    interpretacaoNormal: 'Liderança visionária, carisma e poder de transformar ideias em ação.',
    interpretacaoInvertida: 'Autoritarismo, impulsividade no comando ou ego inflado.',
  },

  {
    id: 51,
    nome: 'Ás de Espadas',
    imagem: require('../assets/images/arcanos/rider-waite/asespadas.png'),
    interpretacaoNormal: 'Clareza mental absoluta, verdade revelada e poder de decisão.',
    interpretacaoInvertida: 'Confusão mental, verdade distorcida ou clareza usada de forma cruel.',
  },
  {
    id: 52,
    nome: '2 de Espadas',
    imagem: require('../assets/images/arcanos/rider-waite/2espadas.png'),
    interpretacaoNormal: 'Pausa antes da decisão, análise cuidadosa e equilíbrio de forças.',
    interpretacaoInvertida: 'Paralisia por análise, negação do problema ou indecisão crônica.',
  },
  {
    id: 53,
    nome: '3 de Espadas',
    imagem: require('../assets/images/arcanos/rider-waite/3espadas.png'),
    interpretacaoNormal: 'Dor necessária que traz clareza e abre espaço para cura.',
    interpretacaoInvertida: 'Ruminação excessiva, mágoa não processada ou vitimização.',
  },
  {
    id: 54,
    nome: '4 de Espadas',
    imagem: require('../assets/images/arcanos/rider-waite/4espadas.png'),
    interpretacaoNormal: 'Descanso restaurador e recolhimento para recuperar as forças.',
    interpretacaoInvertida: 'Estagnação, evasão de responsabilidades ou descanso que virou fuga.',
  },
  {
    id: 55,
    nome: '5 de Espadas',
    imagem: require('../assets/images/arcanos/rider-waite/5espadas.png'),
    interpretacaoNormal: 'Vitória com custo, percepção das consequências das próprias escolhas.',
    interpretacaoInvertida: 'Derrota, humilhação ou conflito que deixou feridas profundas.',
  },
  {
    id: 56,
    nome: '6 de Espadas',
    imagem: require('../assets/images/arcanos/rider-waite/6espadas.png'),
    interpretacaoNormal: 'Transição necessária rumo à paz e águas mais calmas.',
    interpretacaoInvertida: 'Resistência à mudança ou transição turbulenta sem direção clara.',
  },
  {
    id: 57,
    nome: '7 de Espadas',
    imagem: require('../assets/images/arcanos/rider-waite/7espadas.png'),
    interpretacaoNormal: 'Estratégia inteligente, discrição e saber escolher as batalhas.',
    interpretacaoInvertida: 'Desonestidade, traição ou manipulação sendo usada contra você.',
  },
  {
    id: 58,
    nome: '8 de Espadas',
    imagem: require('../assets/images/arcanos/rider-waite/8espadas.png'),
    interpretacaoNormal: 'Reconhecimento das amarras mentais como primeiro passo para a liberdade.',
    interpretacaoInvertida: 'Aprisionamento profundo, vitimismo ou recusa em enxergar a saída.',
  },
  {
    id: 59,
    nome: '9 de Espadas',
    imagem: require('../assets/images/arcanos/rider-waite/9espadas.png'),
    interpretacaoNormal: 'Confronto honesto com medos internos para superá-los.',
    interpretacaoInvertida: 'Ansiedade fora de controle, pesadelos recorrentes ou colapso mental.',
  },
  {
    id: 60,
    nome: '10 de Espadas',
    imagem: require('../assets/images/arcanos/rider-waite/10espadas.png'),
    interpretacaoNormal: 'Fim doloroso de ciclo que abre caminho para reconstrução real.',
    interpretacaoInvertida: 'Drama exagerado, recusa em aceitar o fim ou queda evitável.',
  },
  {
    id: 61,
    nome: 'Page de Espadas',
    imagem: require('../assets/images/arcanos/rider-waite/pageespadas.png'),
    interpretacaoNormal: 'Mente ágil, curiosidade intelectual e busca pela verdade.',
    interpretacaoInvertida: 'Fofoca, uso da inteligência para ferir ou linguagem cortante demais.',
  },
  {
    id: 62,
    nome: 'Cavaleiro de Espadas',
    imagem: require('../assets/images/arcanos/rider-waite/cavespadas.png'),
    interpretacaoNormal: 'Ação direta, foco total e coragem intelectual sem hesitar.',
    interpretacaoInvertida: 'Imprudência verbal, atropelamento dos outros ou agressividade desnecessária.',
  },
  {
    id: 63,
    nome: 'Rainha de Espadas',
    imagem: require('../assets/images/arcanos/rider-waite/rainhaespadas.png'),
    interpretacaoNormal: 'Inteligência afiada, limites saudáveis e julgamento justo.',
    interpretacaoInvertida: 'Frieza excessiva, crueldade ou uso da lógica para se isolar emocionalmente.',
  },
  {
    id: 64,
    nome: 'Rei de Espadas',
    imagem: require('../assets/images/arcanos/rider-waite/reiespadas.png'),
    interpretacaoNormal: 'Autoridade mental, clareza absoluta e decisões baseadas em verdade.',
    interpretacaoInvertida: 'Tirania intelectual, manipulação fria ou uso do poder para oprimir.',
  },

  {
    id: 65,
    nome: 'Ás de Ouros',
    imagem: require('../assets/images/arcanos/rider-waite/asouros.png'),
    interpretacaoNormal: 'Nova oportunidade material, semente de prosperidade e abundância.',
    interpretacaoInvertida: 'Oportunidade perdida, ganância ou projeto sem fundação sólida.',
  },
  {
    id: 66,
    nome: '2 de Ouros',
    imagem: require('../assets/images/arcanos/rider-waite/2ouros.png'),
    interpretacaoNormal: 'Equilíbrio entre demandas práticas com leveza e adaptabilidade.',
    interpretacaoInvertida: 'Desequilíbrio financeiro, sobrecarga ou malabarismo insustentável.',
  },
  {
    id: 67,
    nome: '3 de Ouros',
    imagem: require('../assets/images/arcanos/rider-waite/3ouros.png'),
    interpretacaoNormal: 'Colaboração produtiva, maestria e reconhecimento do talento.',
    interpretacaoInvertida: 'Falta de trabalho em equipe, desvalorização ou esforço sem retorno.',
  },
  {
    id: 68,
    nome: '4 de Ouros',
    imagem: require('../assets/images/arcanos/rider-waite/4ouros.png'),
    interpretacaoNormal: 'Estabilidade conquistada e administração cuidadosa dos recursos.',
    interpretacaoInvertida: 'Avareza, apego excessivo ao controle ou medo paralisante de perder.',
  },
  {
    id: 69,
    nome: '5 de Ouros',
    imagem: require('../assets/images/arcanos/rider-waite/5ouros.png'),
    interpretacaoNormal: 'Período difícil que ensina resiliência e humildade para pedir ajuda.',
    interpretacaoInvertida: 'Miséria prolongada por orgulho ou recusa em aceitar suporte disponível.',
  },
  {
    id: 70,
    nome: '6 de Ouros',
    imagem: require('../assets/images/arcanos/rider-waite/6ouros.png'),
    interpretacaoNormal: 'Generosidade equilibrada, fluxo saudável de dar e receber.',
    interpretacaoInvertida: 'Desequilíbrio na troca, caridade com controle ou dívida emocional.',
  },
  {
    id: 71,
    nome: '7 de Ouros',
    imagem: require('../assets/images/arcanos/rider-waite/7ouros.png'),
    interpretacaoNormal: 'Paciência recompensada, avaliação honesta e colheita no tempo certo.',
    interpretacaoInvertida: 'Impaciência, investimento sem retorno ou esforço mal direcionado.',
  },
  {
    id: 72,
    nome: '8 de Ouros',
    imagem: require('../assets/images/arcanos/rider-waite/8ouros.png'),
    interpretacaoNormal: 'Dedicação ao ofício, aperfeiçoamento e maestria pelo esforço diário.',
    interpretacaoInvertida: 'Perfeccionismo paralisante, trabalho sem qualidade ou esforço vazio.',
  },
  {
    id: 73,
    nome: '9 de Ouros',
    imagem: require('../assets/images/arcanos/rider-waite/9ouros.png'),
    interpretacaoNormal: 'Independência conquistada, abundância e prazer nos próprios frutos.',
    interpretacaoInvertida: 'Dependência financeira, luxo superficial ou solidão na prosperidade.',
  },
  {
    id: 74,
    nome: '10 de Ouros',
    imagem: require('../assets/images/arcanos/rider-waite/10ouros.png'),
    interpretacaoNormal: 'Riqueza duradoura, legado familiar e segurança que atravessa gerações.',
    interpretacaoInvertida: 'Conflitos por herança, instabilidade financeira ou valores familiares abalados.',
  },
  {
    id: 75,
    nome: 'Page de Ouros',
    imagem: require('../assets/images/arcanos/rider-waite/pageouros.png'),
    interpretacaoNormal: 'Aprendizado prático, novas habilidades e projetos com potencial real.',
    interpretacaoInvertida: 'Falta de foco, procrastinação ou aprendizado sem aplicação prática.',
  },
  {
    id: 76,
    nome: 'Cavaleiro de Ouros',
    imagem: require('../assets/images/arcanos/rider-waite/cavouros.png'),
    interpretacaoNormal: 'Persistência inabalável, rotina produtiva e progresso constante.',
    interpretacaoInvertida: 'Teimosia, estagnação por excesso de cautela ou rigidez sem flexibilidade.',
  },
  {
    id: 77,
    nome: 'Rainha de Ouros',
    imagem: require('../assets/images/arcanos/rider-waite/rainhaouros.png'),
    interpretacaoNormal: 'Praticidade nutrida, conforto abundante e gestão de recursos com maestria.',
    interpretacaoInvertida: 'Materialismo excessivo, controle pelo conforto ou negligência emocional.',
  },
  {
    id: 78,
    nome: 'Rei de Ouros',
    imagem: require('../assets/images/arcanos/rider-waite/reiouros.png'),
    interpretacaoNormal: 'Poder material consolidado, prosperidade e capacidade de gerar riqueza.',
    interpretacaoInvertida: 'Ganância, corrupção ou uso do poder financeiro para dominar os outros.',
  },
];


export const TAROT_CARDS_COMPLETO: TarotCard[] = [...TAROT_CARDS, ...TAROT_MINOR_CARDS];

export const HOROSCOPO_DIARIO: Record<SignoNome, string[]> = {
  Áries: [
    'Hoje você ganha força quando age com foco em uma meta só.',
    'Evite responder no impulso: estratégia vale mais que velocidade.',
  ],
  Touro: [
    'A constância de hoje abre resultado concreto nos próximos dias.',
    'Um ajuste pequeno na rotina pode trazer grande conforto.',
  ],
  Gêmeos: [
    'Uma conversa certa muda completamente sua perspectiva.',
    'Canalize sua curiosidade em uma prioridade para render melhor.',
  ],
  Câncer: [
    'Seu cuidado com os detalhes emocionais fortalece vínculos.',
    'Proteja sua energia sem se fechar para novas trocas.',
  ],
  Leão: [
    'Seu brilho aumenta quando você compartilha protagonismo.',
    'Mostre seu trabalho com confiança, sem precisar provar nada.',
  ],
  Virgem: [
    'Organizar o ambiente vai destravar sua mente hoje.',
    'Confie no processo: perfeição pode esperar, consistência não.',
  ],
  Libra: [
    'Diplomacia será seu diferencial em decisões importantes.',
    'Escolher por você também é um ato de equilíbrio.',
  ],
  Escorpião: [
    'A profundidade que você sente hoje revela um caminho real.',
    'Transforme intensidade em ação prática e objetiva.',
  ],
  Sagitário: [
    'Sua visão de futuro inspira quem está à sua volta.',
    'Aventurar com responsabilidade rende melhores descobertas.',
  ],
  Capricórnio: [
    'Disciplina hoje gera segurança amanhã.',
    'Priorize o essencial: menos tarefas, mais entrega.',
  ],
  Aquário: [
    'Uma ideia fora do padrão pode virar solução central.',
    'Conexões com pessoas diferentes ampliam suas oportunidades.',
  ],
  Peixes: [
    'Sua intuição está afiada, use-a junto com fatos.',
    'Criatividade e sensibilidade serão sua vantagem no dia.',
  ],
};

export const CIGANO_CARDS: TarotCard[] = [
  {
    id: 101,
    nome: 'O Mensageiro',
    imagem: require('../assets/images/arcanos/cigano/mensageiro.png'),
    interpretacaoNormal: 'Notícias chegando, movimento e rapidez.',
    interpretacaoInvertida: 'Atrasos, mensagens perdidas ou hesitação.',
  },
  {
    id: 102,
    nome: 'O Navio',
    imagem: require('../assets/images/arcanos/cigano/navio.png'),
    interpretacaoNormal: 'Mudanças, viagens e novos horizontes a longo prazo.',
    interpretacaoInvertida: 'Instabilidade, insegurança ou planos de viagem adiados.',
  },
  {
    id: 103,
    nome: 'A Casa',
    imagem: require('../assets/images/arcanos/cigano/casa.png'),
    interpretacaoNormal: 'Equilíbrio, família, lar e estabilidade pessoal.',
    interpretacaoInvertida: 'Desequilíbrio familiar ou problemas estruturais no lar.',
  },
  {
    id: 104,
    nome: 'As Nuvens',
    imagem: require('../assets/images/arcanos/cigano/nuvens.png'),
    interpretacaoNormal: 'Dúvidas passageiras e instabilidade mental.',
    interpretacaoInvertida: 'Confusão persistente ou falta de clareza nas decisões.',
  },
  {
    id: 105,
    nome: 'A Torre',
    imagem: require('../assets/images/arcanos/cigano/torre.png'),
    interpretacaoNormal: 'Isolamento estratégico, espiritualidade ou autoconhecimento.',
    interpretacaoInvertida: 'Solidão excessiva ou afastamento social forçado.',
  },
  {
    id: 106,
    nome: 'O Buquê',
    imagem: require('../assets/images/arcanos/cigano/buque.png'),
    interpretacaoNormal: 'Felicidade, gratidão, beleza e surpresas positivas.',
    interpretacaoInvertida: 'Felicidade passageira ou falta de reconhecimento.',
  },
  {
    id: 107,
    nome: 'A Cegonha',
    imagem: require('../assets/images/arcanos/cigano/cegonha.png'),
    interpretacaoNormal: 'Novidades, gravidez (literal ou de ideias) e transições.',
    interpretacaoInvertida: 'Resistência a mudanças ou projetos interrompidos.',
  },
  {
    id: 108,
    nome: 'A Estrela',
    imagem: require('../assets/images/arcanos/cigano/estrela.png'),
    interpretacaoNormal: 'Sorte, proteção espiritual e caminhos iluminados.',
    interpretacaoInvertida: 'Falta de foco, desânimo ou perda de conexão espiritual.',
  },
  {
    id: 109,
    nome: 'O Jardim',
    imagem: require('../assets/images/arcanos/cigano/jardim.png'),
    interpretacaoNormal: 'Vida social, eventos públicos e colheita do que foi plantado.',
    interpretacaoInvertida: 'Isolamento social ou colheita insatisfatória.',
  },
  {
    id: 110,
    nome: 'O Coração',
    imagem: require('../assets/images/arcanos/cigano/coracao.png'),
    interpretacaoNormal: 'Amor, paixão, entrega emocional e sentimentos verdadeiros.',
    interpretacaoInvertida: 'Instabilidade emocional ou mágoas profundas.',
  },
  {
    id: 111,
    nome: 'O Sol',
    imagem: require('../assets/images/arcanos/cigano/sol.png'),
    interpretacaoNormal: 'Sucesso absoluto, energia vital e clareza total.',
    interpretacaoInvertida: 'Excesso de orgulho ou vitalidade baixa.',
  },
  {
    id: 112,
    nome: 'A Cruz',
    imagem: require('../assets/images/arcanos/cigano/cruz.png'),
    interpretacaoNormal: 'Destino, provação necessária e finalização de carma.',
    interpretacaoInvertida: 'Fardo pesado demais ou sofrimento prolongado por teimosia.',
  },
];

export const MARSELHA_CARDS: TarotCard[] = [
  {
    id: 201,
    nome: 'O Louco',
    imagem: require('../assets/images/arcanos/marselha/louco.png'),
    interpretacaoNormal: 'Irresponsabilidade consciente e entrega ao destino.',
    interpretacaoInvertida: 'Falta de rumo, caos ou fuga da realidade.',
  },
  {
    id: 202,
    nome: 'O Mago',
    imagem: require('../assets/images/arcanos/marselha/mago.png'),
    interpretacaoNormal: 'Potencial infinito e as ferramentas para o início.',
    interpretacaoInvertida: 'Trapaça, falta de preparo ou talentos desperdiçados.',
  },
  {
    id: 203,
    nome: 'A Papisa',
    imagem: require('../assets/images/arcanos/marselha/papisa.png'),
    interpretacaoNormal: 'Estudo, gestação e sabedoria silenciosa.',
    interpretacaoInvertida: 'Segredos revelados de forma brusca ou passividade.',
  },
  {
    id: 204,
    nome: 'A Imperatriz',
    imagem: require('../assets/images/arcanos/marselha/imperatriz.png'),
    interpretacaoNormal: 'Poder de comunicação e abundância criativa.',
    interpretacaoInvertida: 'Futilidade, vaidade ou problemas de expressão.',
  },
  {
    id: 205,
    nome: 'O Imperador',
    imagem: require('../assets/images/arcanos/marselha/imperador.png'),
    interpretacaoNormal: 'Estabilidade, autoridade e concretização material.',
    interpretacaoInvertida: 'Tirania, instabilidade ou fraqueza de caráter.',
  },
  {
    id: 206,
    nome: 'O Papa',
    imagem: require('../assets/images/arcanos/marselha/papa.png'),
    interpretacaoNormal: 'Conexão espiritual, ensino e mediação.',
    interpretacaoInvertida: 'Falsos conselhos, fanatismo ou má influência.',
  },
  {
    id: 207,
    nome: 'Os Enamorados',
    imagem: require('../assets/images/arcanos/marselha/enamorados.png'),
    interpretacaoNormal: 'Afinidades, desejos e a prova da escolha.',
    interpretacaoInvertida: 'Tentação perigosa ou incapacidade de decidir.',
  },
  {
    id: 208,
    nome: 'O Carro',
    imagem: require('../assets/images/arcanos/marselha/carro.png'),
    interpretacaoNormal: 'Triunfo, sucesso e domínio sobre as emoções.',
    interpretacaoInvertida: 'Derrota, falta de controle ou planos frustrados.',
  },
  {
    id: 209,
    nome: 'A Justiça',
    imagem: require('../assets/images/arcanos/marselha/justica.png'),
    interpretacaoNormal: 'Equilíbrio necessário, rigor e colheita justa.',
    interpretacaoInvertida: 'Injustiça, complicações legais ou desequilíbrio.',
  },
  {
    id: 210,
    nome: 'O Eremita',
    imagem: require('../assets/images/arcanos/marselha/eremita.png'),
    interpretacaoNormal: 'Solidão buscada, prudência e tempo de amadurecer.',
    interpretacaoInvertida: 'Rancor, teimosia ou isolamento improdutivo.',
  },
  {
    id: 211,
    nome: 'A Roda da Fortuna',
    imagem: require('../assets/images/arcanos/marselha/roda.png'),
    interpretacaoNormal: 'Ciclos que se fecham e novos que começam.',
    interpretacaoInvertida: 'Bloqueios externos ou resistência ao destino.',
  },
  {
    id: 212,
    nome: 'A Força',
    imagem: require('../assets/images/arcanos/marselha/forca.png'),
    interpretacaoNormal: 'Inteligência vencendo a força bruta; autocontrole.',
    interpretacaoInvertida: 'Violência, fraqueza ou impulsividade animal.',
  },
  {
    id: 213,
    nome: 'O Pendurado',
    imagem: require('../assets/images/arcanos/marselha/pendurado.png'),
    interpretacaoNormal: 'Sacrifício por um bem maior e suspensão.',
    interpretacaoInvertida: 'Esforço inútil, martírio ou falta de ação.',
  },
  {
    id: 214,
    nome: 'A Morte (13)',
    imagem: require('../assets/images/arcanos/marselha/13.png'),
    interpretacaoNormal: 'Limpeza necessária para o novo surgir.',
    interpretacaoInvertida: 'Estagnação dolorosa ou medo da mudança.',
  },
  {
    id: 215,
    nome: 'A Temperança',
    imagem: require('../assets/images/arcanos/marselha/temperanca.png'),
    interpretacaoNormal: 'Alquimia interna, cura e moderação.',
    interpretacaoInvertida: 'Falta de tato, conflitos ou excessos.',
  },
  {
    id: 216,
    nome: 'O Diabo',
    imagem: require('../assets/images/arcanos/marselha/diabo.png'),
    interpretacaoNormal: 'Paixões intensas, magnetismo e desejos materiais.',
    interpretacaoInvertida: 'Obsessão, prisões mentais ou abuso de poder.',
  },
  {
    id: 217,
    nome: 'A Torre',
    imagem: require('../assets/images/arcanos/marselha/torre.png'),
    interpretacaoNormal: 'A Casa de Deus; libertação de ilusões.',
    interpretacaoInvertida: 'Desastre evitável ou orgulho que gera queda.',
  },
  {
    id: 218,
    nome: 'A Estrela',
    imagem: require('../assets/images/arcanos/marselha/estrela.png'),
    interpretacaoNormal: 'Sorte, pureza e destino brilhante.',
    interpretacaoInvertida: 'Promessas não cumpridas ou falta de esperança.',
  },
  {
    id: 219,
    nome: 'A Lua',
    imagem: require('../assets/images/arcanos/marselha/lua.png'),
    interpretacaoNormal: 'Intuição profunda, reflexão e sonhos.',
    interpretacaoInvertida: 'Traições ocultas, pesadelos ou confusão.',
  },
  {
    id: 220,
    nome: 'O Sol',
    imagem: require('../assets/images/arcanos/marselha/sol.png'),
    interpretacaoNormal: 'Fraternidade, sucesso e clareza espiritual.',
    interpretacaoInvertida: 'Ofuscamento, vaidade ou clareza parcial.',
  },
  {
    id: 221,
    nome: 'O Julgamento',
    imagem: require('../assets/images/arcanos/marselha/julgamento.png'),
    interpretacaoNormal: 'O despertar, chamado para a verdade.',
    interpretacaoInvertida: 'Dificuldade em ouvir a própria consciência.',
  },
  {
    id: 222,
    nome: 'O Mundo',
    imagem: require('../assets/images/arcanos/marselha/mundo.png'),
    interpretacaoNormal: 'O êxito supremo e a totalidade do ser.',
    interpretacaoInvertida: 'Insucesso por falta de visão ou imperfeição.',
  },
];

export function getPrevisaoDoDia(signo: SignoNome, date = new Date()): string {
  const lista = HOROSCOPO_DIARIO[signo] ?? ['Hoje é um bom dia para confiar no seu processo.'];
  const idx = date.getDate() % lista.length;
  return lista[idx];
}
