import { StyleSheet } from 'react-native';
import { Colors } from '../GlobalStyles';

export const tiragemScreenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.deepBlue },
  page: {
    padding: 18,
    paddingBottom: 56,
    backgroundColor: Colors.deepBlue,
  },
  kicker: {
    color: Colors.gold,
    textAlign: 'center',
    letterSpacing: 1,
    fontSize: 11,
    opacity: 0.9,
    marginTop: 6,
  },
  block: {
    borderWidth: 1,
    borderColor: 'rgba(228,195,38,0.24)',
    borderRadius: 18,
    padding: 14,
    marginBottom: 14,
    backgroundColor: 'rgba(38,17,51,0.82)',
  },
  blockTitle: {
    color: Colors.gold,
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 8,
  },
  baseText: {
    color: Colors.text,
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: 'rgba(228,195,38,0.2)',
    borderRadius: 16,
    minHeight: 88,
    padding: 14,
    color: Colors.text,
    marginBottom: 10,
    textAlignVertical: 'top',
    backgroundColor: 'rgba(12,7,20,0.38)',
  },
  selectorLabel: {
    color: Colors.text,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.4,
    marginBottom: 6,
    marginTop: 4,
    textTransform: 'uppercase',
    opacity: 0.8,
  },
  questionText: {
    color: '#fff',
    fontSize: 14,
    marginBottom: 10,
  },
  dropdownButton: {
    borderWidth: 1,
    borderColor: 'rgba(228,195,38,0.24)',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 10,
    backgroundColor: 'rgba(12,7,20,0.36)',
  },
  dropdownTitle: {
    color: Colors.gold,
    fontWeight: '700',
  },
  dropdownList: {
    marginBottom: 10,
    backgroundColor: 'transparent',
  },
  dropdownItem: {
    borderWidth: 1,
    borderColor: 'rgba(228,195,38,0.14)',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 10,
    marginBottom: 8,
    backgroundColor: 'rgba(12,7,20,0.34)',
  },
  dropdownItemHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  dropdownItemMain: {
    flex: 1,
    backgroundColor: 'transparent',
    marginRight: 10,
  },
  dropdownItemActive: {
    borderColor: 'rgba(228,195,38,0.7)',
    backgroundColor: 'rgba(46,22,61,0.8)',
  },
  dropdownItemTitle: {
    color: Colors.gold,
    fontWeight: '700',
    marginBottom: 4,
  },
  dropdownItemText: {
    color: Colors.text,
    fontSize: 13,
  },
  favoriteButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(228,195,38,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(228,195,38,0.18)',
  },
  favoriteButtonText: {
    color: Colors.gray,
    fontSize: 18,
  },
  favoriteButtonTextActive: {
    color: Colors.gold,
  },
  favoriteTag: {
    color: Colors.gold,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.6,
    marginTop: 6,
    textTransform: 'uppercase',
  },
  card: {
    borderWidth: 1,
    borderColor: 'rgba(228,195,38,0.22)',
    borderRadius: 14,
    padding: 10,
    marginBottom: 10,
    backgroundColor: 'rgba(12,7,20,0.42)',
  },
  noteBlock: {
    marginTop: 8,
    paddingTop: 4,
  },
  noteTitle: {
    color: Colors.gold,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 8,
  },
  noteInput: {
    borderWidth: 1,
    borderColor: 'rgba(228,195,38,0.2)',
    borderRadius: 16,
    minHeight: 110,
    padding: 14,
    color: Colors.text,
    marginBottom: 10,
    textAlignVertical: 'top',
    backgroundColor: 'rgba(12,7,20,0.38)',
  },
  cardTitle: {
    color: Colors.gold,
    fontWeight: '700',
    marginBottom: 6,
  },
  readingCardImage: {
    width: '100%',
    height: 170,
    marginBottom: 6,
  },

  favoritesSectionButton: {
    backgroundColor: 'rgba(228,195,38,0.06)',
    borderColor: 'rgba(228,195,38,0.3)',
  },
  nestedDropdownList: {
    marginBottom: 8,
    paddingLeft: 12,
    backgroundColor: 'transparent',
  },
  demaisTiragensSectionTitle: {
    color: Colors.gold,
    fontSize: 13,
    fontWeight: '600',
    marginTop: 8,
    marginBottom: 8,
    paddingHorizontal: 4,
    opacity: 0.8,
  },
});
